name: Release Builds

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            artifact_name: RedShift-macos-x64
          - os: macos-14
            artifact_name: RedShift-macos-arm64
          - os: windows-latest
            artifact_name: RedShift-windows-x64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt -r requirements-build.txt

      - name: Build app
        run: python build_release.py

      - name: Archive macOS app
        if: runner.os == 'macOS'
        run: ditto -c -k --keepParent dist/RedShift.app dist/${{ matrix.artifact_name }}.zip

      - name: Archive Windows app
        if: runner.os == 'Windows'
        shell: pwsh
        run: Compress-Archive -Path dist/RedShift/* -DestinationPath dist/${{ matrix.artifact_name }}.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/*.zip
